//Concrete Strategy
public class WeatherForecastType1 implements StrategyDesignPattern_WeatherService {
    
    Public Double getTemperatureInCelcius(){
     	Double temperature;
        //Temperature logic goes here 
        return temperature;
        
    }
    Public Double getTemperatureInFarhenheit(){
        Double temperature;
        //Temperature logic
        return temperature;
    }

}